### ISSUE TITLE
Tag 插件使用过程中遇到的问题反馈

### ISSUE THREAD

**Issue by WangChao2021** [typora-community-plugin/typora-plugin-tag#1]
看到插件市场上能支持 Tag，真是一个伟大的设计，要是能支持得更完整就更完善了

1. 这里的 Tag 列表，要是能支持双击过滤出所有带此tag的文章列表就好（简单点可以通过调用Typora搜索功能，搜索tag进行过滤）
![Clip_2024-07-04_15-34-51](https://github.com/typora-community-plugin/typora-plugin-tag/assets/95513088/bf5aef0b-2799-415d-9562-47ec7c1c9795)

2. 另外这里的tag列表未清空时，tag插件无法删除，删除时无反应，也没任何提示，后面猜想是不是因为存在tag所以不允许删除，结果果然如此。这里可以优化下，删除 tag 插件时如果不允许直接删除，需要明确提示“存在tag建议数据，请先删除后tag数据后再重试”；或者删除时，提示“删除tag插件将连同tag建议数据一同删除”，确认后直接连同tag数据一同删除。
![Clip_2024-07-04_15-36-44](https://github.com/typora-community-plugin/typora-plugin-tag/assets/95513088/fcf14e94-c1d2-4264-ae9e-606037cb1e46)

**Comment by plylrnsdy** [comment]
1. typora-community-plugin/core 设计的有点问题，现在不好调用搜索，需要先改改 core
2. ~~这个好像是没刷新，其实已经删了~~ 理解错了

**Comment by plylrnsdy** [comment]
1. 先更新 typora-community-plugin/core 到 2.0.17，再更新 tag 插件到 1.6.1。现在可以通过点击搜索按钮，转到搜索面板进行搜索
2. 上次理解错了，但是没发现什么问题（也没改什么），插件可以正常删除……你装新版测试一下
